# --- States ---
IDLE = "IDLE"
BUSY = "BUSY"
COMPLETED = "COMPLETED"
DRONE_FAILED = "DRONE_FAILED"
TASK_FAILED = "TASK_FAILED"

# --- Events / Commands ---
ASSIGN_TASK = "ASSIGN_TASK"
ACK = "ACK"
REJECTED = "REJECTED"
START_TASK = "START_TASK"
CANCEL_TASK = "CANCEL_TASK"
STATE_CHANGED = "STATE_CHANGED"
COMPLETED_EVENT = "COMPLETED"
TASK_FAILED_EVENT = "TASK_FAILED"
DRONE_FAILED_EVENT = "DRONE_FAILED"
STOP = "STOP"